name: alchemy
description: An Alchemy Platform client for Flutter & Dart
version: 0.0.1
homepage: https://github.com/oliverbytes/alchemy

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  console_mixin: ^0.0.1
  logger: ^1.1.0
  either_dart: ^0.1.4
  # NETWORK
  dio: ^4.0.3
  json_rpc_2: ^3.0.1
  web_socket_channel: ^2.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
